### ISSUE TITLE
Añadir CI

### ISSUE THREAD

**Issue by marreA** [PAL-ULL/software-metco#4]
Dado que el repositorio se ha establecido como público, creo que es un buen momento para emplear un sistema de CI como Travis-CI. De esta forma, cualquiera persona que quiera instalar METCO por primera vez y comenzar a emplear la herramienta tenga la seguridad de que le se instalará correctamente.

La instalación en una nueva máquina fue un problema que se relató hace como en #2 y con Travis-CI tendríamos una herramienta que nos ayudaría a solventar problemas de este estilo. 

Además, ya me he preocupado en generar un fichero _.travis.yml_ para configurar las integraciones de METCO con Travis-CI por lo que solo faltaría añadir el proyecto en la plataforma.

@coromoto @crguezl @algorithms-ull

**Comment by crguezl** [comment]
¡Genial!

**Comment by marreA** [comment]
Alguien de la organización tendrá que incluir el repositorio en Travis-ci.org dado que yo no puedo hacerlo. No formo parte de la organización y solo estoy como colaborador del repositorio.  @crguezl

**Comment by crguezl** [comment]
Hola @marreA y @coromoto y @algorithms-ull 

Te he hecho miembro de la organización. 
He autorizado a Travis el acceso a la organización.

Espero que funcione

Cualquier cosa, me dices

**Comment by crguezl** [comment]
Uff....

![captura de pantalla 2018-11-19 a las 13 57 05](https://user-images.githubusercontent.com/1142554/48711429-2d11d300-ec03-11e8-9ef2-99da2b5f546b.png)

Parece que hay un problema justo con este repo

**Comment by crguezl** [comment]
Dice que no lo migra a ci.com.
Aunque ci.com es la plataforma de pago, lo que me tiene preocupado.
De todos modos, el build de CI se puede ver cliqueando

**Comment by marreA** [comment]
Hola @crguezl , @coromoto, el problema está en la URL de Travis, la web Travis-ci.com es para repositorios privados y como METCO es público ahora tienen que buscarlo en Travis-ci.org. Es una jaleo lo de las direcciones.

Aquí el estado: https://travis-ci.org/PAL-ULL/software-metco/

**Comment by crguezl** [comment]
No se si nos dejarán tenerlos en ci.com por mucho tiempo.

![captura de pantalla 2018-11-19 a las 14 03 09](https://user-images.githubusercontent.com/1142554/48711731-e2dd2180-ec03-11e8-9622-766bd0ed3c8e.png)

**Comment by marreA** [comment]
En ci.com puedes tener repositorios privados pero con una limitación de actualizaciones.

En principio admiten hasta 100 builds [doc](https://docs.travis-ci.com/user/travis-ci-for-private/#does-travis-ci-for-private-repositories-include-a-trial-period). 

Según he leído, planean [mover ci.org a ci.com gradualmente](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/) pero si la herramienta sigue siendo Open Source no habrá problema.
