### ISSUE TITLE
Función Ackley no se ejecuta

### ISSUE THREAD

**Issue by miordev** [PAL-ULL/software-metco#6]
### **Entorno**

Estoy utilizando el sistema operativo windows10 con la terminal de linux wsl2 con las distribución Debian

### **Preparación**

En la dirección software-metco/doc/output.md del repositorio se encuentra un ejemplo de ejecución, tal que

`./metcoSeq /home/username . PlainText results.txt MonoDE Ackley EVALUATIONS 100000 1000 0 0.5 0.115 30 ! 30 $ NoOp;`

Luego, cambio la ruta /home/username por la mia, quedando

`./metcoSeq /mnt/c/Users/Usuario/Desktop . PlainText results.txt MonoDE Ackley EVALUATIONS 100000 1000 0 0.5 0.115 30 ! 30 $ NoOp;`

### **Ejecución**

Al ejecutarlo, me muestra el siguiente error por consola.

```
./Ackley.so: cannot open shared object file: No such file or directory
Plugin Problem::Ackley file could not be opened: ./Ackley.so
Error loading individual
```

### **Cabe destacar**

Por otro lado, el ejemplo que se encuentra en la dirección software-metco/doc/setup.md del repositorio, que es

`./metcoSeq /home/username . PlainText results.txt OBL_CPSO Rastrigin EVALUATIONS 1000 100 0 0.5 30 ! 30 $ NoOp;`

Si me funciona al ejecutarlo y genera el archivo results.txt

**Comment by amarrerod** [comment]
El problema es que la función Ackley no está implementada en las últimas versiones de METCO, por eso no funciona. En cambio, la función Rastrigin sí que se encuentra implementada. Puedes comprobar todos los problemas implementados en el directorio oplink/algorithms/team/src/plugins/problems.
